version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/awsdag
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
checksum:
  name_template: "checksums.txt"
archives:
  - format_overrides:
      - goos: windows
        formats: [zip]
nfpms:
  - file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    homepage: https://github.com/winebarrel/awsdag
    description: Sign in to AWS IAM Identity Center from a machine with no browser.
    license: CC0-1.0
    maintainer: "Genki Sugawara <sugawara@winebarrel.jp>"
    formats:
      - apk
      - deb
      - rpm
